name: Check for New Repositories

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  extract_mapping_job:
    runs-on: ubuntu-latest
    outputs:
      filtered_mapping: ${{ steps.extract_mapping.outputs.filtered_mapping }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Extract intersphinx_mapping
        id: extract_mapping
        run: |
          filtered_mapping=$(python -c '
          with open("source/conf.py", "r") as f:
            conf_content = f.read()
            
          # Find the start and end of the intersphinx_mapping block
          start_idx = conf_content.find("intersphinx_mapping")
          end_idx = conf_content.find("}", start_idx)
          
          # Extract the block
          mapping_block = conf_content[start_idx:end_idx+1]
          
          # Find the start and end of the dictionary
          start_idx = mapping_block.find("{")
          end_idx = mapping_block.rfind("}")

          # Extract the dictionary part
          dictionary_string = mapping_block[start_idx:end_idx + 1]

          # Parse the dictionary string
          mapping_dict = eval(dictionary_string)

          # Extract keys from the dictionary
          filtered_mapping = list(mapping_dict.keys())
          echo "${filtered_mapping[@]}"
          ')

  list_repos_job:
    runs-on: ubuntu-latest
    outputs:
      repo_names: ${{ steps.list_repos.outputs.repo_names }}
    steps:
      - name: List Repositories
        id: list_repos
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.listForOrg({
              org: 'salt-extensions',
              per_page: 100
            });
            return response.data.map(repo => repo.name);

      - name: Set output
        run: echo "::set-output name=repo_names::${{ steps.list_repos.outputs.result }}"

  compare_repositories_job:
    runs-on: ubuntu-latest
    needs: [extract_mapping_job, list_repos_job]
    steps:
      - name: Debug Intersphinx Mapping
        run: |
          echo "Intersphinx Mapping: ${{ needs.extract_mapping_job.outputs.filtered_mapping }}"
      
      - name: Debug Repos
        run: |
          echo "Repos: ${{ needs.list_repos_job.outputs.repo_names }}"    

      - name: Compare Repositories
        run: |
          for repo in ${{ needs.list_repos_job.outputs.repo_names }}; do
            if ! echo "${{ needs.extract_mapping_job.outputs.filtered_mapping }}" | grep -q "$repo"; then
              echo "Repository $repo is missing from Intersphinx Mapping."
            fi
          done
