name: Check for New Repositories

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  check_for_new_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Extract intersphinx_mapping
        run: |
          python -c "
          with open('source/conf.py', 'r') as f:
            conf_content = f.read()
    
          # Find the start and end of the intersphinx_mapping block
          start_idx = conf_content.find('intersphinx_mapping')
          end_idx = conf_content.find(')', start_idx)
    
          # Extract the block
          mapping_block = conf_content[start_idx:end_idx+1]
    
          # Split the block into lines and remove the line containing intersphinx_mapping
          lines = mapping_block.split('\n')
          filtered_lines = [line for line in lines if 'intersphinx_mapping' not in line]
    
          # Join the lines back together and print
          filtered_mapping = '\n'.join(filtered_lines)
          print(filtered_mapping)
          "
      
      - name: List Repositories
        id: list_repos
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.listForOrg({
              org: 'salt-extensions',
              per_page: 100
            });
            return response.data.map(repo => repo.name);
      
  