name: Check for New Repositories

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  check_for_new_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      
      - name: List Repositories
        id: list_repos
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.listForOrg({
              org: 'salt-extensions',
              per_page: 100
            });
            return response.data.map(repo => repo.name);
      
      - name: Extract Intersphinx Mapping from conf.py
        id: extract_mapping
        run: |
          INTERSPHINX_MAPPING=$(grep -A 10 "intersphinx_mapping" source/conf.py | grep -v "intersphinx_mapping" | sed -e 's/^[[:space:]]*//' | tr -d '\n' | sed 's/"/\\"/g')
          echo "INTERSPHINX_MAPPING=\"$INTERSPHINX_MAPPING\"" >> $GITHUB_ENV
        
    
      - name: Print Intersphinx Mapping
        run: echo "${{ env.INTERSPHINX_MAPPING }}"

      - name: Compare with Intersphinx Mapping
        id: compare_repos
        run: |
          INTERSPHINX_MAPPING="${{ env.INTERSPHINX_MAPPING }}"
          for repo in "${{ steps.list_repos.outputs.result }}"; do
          if [[ ! $INTERSPHINX_MAPPING =~ \"$repo\" ]]; then
            echo "Repository $repo is missing from Intersphinx Mapping."
          fi
          done