name: Check for New Repositories

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  check_for_new_repos:
    runs-on: ubuntu-latest

    steps:
      - name: List Repositories
        id: list_repos
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.listForOrg({
              org: 'salt-extensions',
              per_page: 100
            });
            return response.data.map(repo => repo.name);
      
      - name: Check Intersphinx Mapping
        run: |
          echo "Checking intersphinx mapping..."

          # Read the intersphinx mapping from your central docs repository
          # You'll need to replace `path/to/intersphinx_mapping.py` with the actual path
          # of your intersphinx mapping file.
          
          mapping=$(grep -oP "(?<=intersphinx_mapping = ).*" source/conf.py)

          # Loop through fetched repositories and check if they are listed in the mapping
          
          for repo in "${{ steps.list_repos.outputs.result }}"; do
            if [[ ! $mapping =~ "$repo" ]]; then
              echo "Repository '$repo' is missing from the intersphinx mapping."
              # Optionally, add logic to update the mapping automatically
            fi
          done