name: Check for New Repositories

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  check_for_new_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Extract intersphinx_mapping
        id: extract_mapping
        run: |
          filtered_mapping_keys=$(python -c "
          import ast
      
          # Define the filtered_mapping string
          filtered_mapping_str = \"\"\"${{ filtered_mapping }}\"\"\"
          
          # Parse the filtered_mapping string as a dictionary
          filtered_mapping_dict = ast.literal_eval(filtered_mapping_str)
          
          # Extract keys and convert them to a list
          keys_list = list(filtered_mapping_dict.keys())
          
          # Format keys as an array string
          keys_array_str = '[\"' + '\",\"'.join(keys_list) + '\"]'
          
          # Print the array string
          print(keys_array_str)
          ")
          echo $filtered_mapping_keys
          
          
          
        
      
      - name: List Repositories
        id: list_repos
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.listForOrg({
              org: 'salt-extensions',
              per_page: 100
            });
            return response.data.map(repo => repo.name);

      - name: Debug Intersphinx Mapping
        run: |
          echo "Intersphinx Mapping: ${{ steps.extract_mapping.outputs.intersphinx_mapping }}"
      
      - name: Debug Intersphinx Mapping
        run: |
          echo "repos: ${{ steps.list_repos.outputs.result }}"    

      - name: Compare Repositories
        run: |
          for repo in ${{ steps.list_repos.outputs.result }}; do
          if ! echo "${{ steps.extract_mapping.outputs.intersphinx_mapping }}" | grep -q "$repo"; then
          echo "Repository $repo is missing from Intersphinx Mapping."
          fi
          done
